name: FeatherCore
version: 0.2.8
main: mc.owls.valley.net.feathercore.core.FeatherCore
author: DefaultyBuf
description: Core plugin for server bukkit/spigot/paper servers

depend: [Vault]

api-version: 1.21.1

feathercore:
  configs:
    - field: dataConfigFile
      config: data.yml
    - field: economyConfigFile
      config: economy.yml
    - field: messagesConfigFile
      config: messages.yml
  modules:
    - name: ConfigurationManager
      class: mc.owls.valley.net.feathercore.core.common.ConfigurationManager
      mandatory: true
      dependencies: []
    - name: MongoModule
      class: mc.owls.valley.net.feathercore.modules.data.mongodb.MongoModule
      mandatory: true
      dependencies: [ConfigurationManager]
    - name: PlayersDataModule
      class: mc.owls.valley.net.feathercore.modules.data.players.PlayersDataModule
      mandatory: true
      dependencies: [ConfigurationManager, MongoModule]
    - name: FeatherEconomyProviderModule
      class: mc.owls.valley.net.feathercore.modules.economy.provider.FeatherEconomyProviderModule
      mandatory: true
      dependencies: [PlayersDataModule]
    - name: VaultModule
      class: mc.owls.valley.net.feathercore.modules.economy.vault.VaultModule
      mandatory: true
      dependencies: [FeatherEconomyProviderModule]
    - name: CommandsRegistrator
      class: mc.owls.valley.net.feathercore.core.common.CommandsRegistrator
      mandatory: true
      dependencies: [ConfigurationManager, MongoModule, PlayersDataModule, FeatherEconomyProviderModule, VaultModule]
    - name: ListenersRegistrator
      class: mc.owls.valley.net.feathercore.core.common.ListenersRegistrator
      mandatory: true
      dependencies: [ConfigurationManager, MongoModule, PlayersDataModule, FeatherEconomyProviderModule, VaultModule]
  listeners:
    - mc.owls.valley.net.feathercore.modules.data.players.listeners.PlayerJoinDataListener
    - mc.owls.valley.net.feathercore.modules.economy.listeners.BanknotePlaceListener

commands:
  balance:
    description: State the current balance of a given player
    usage: /balance <player>
    aliases: [bal]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.BalanceCommand
  eco:
    description: Manage server economy
    usage: /eco give/take/set/reset [player] [amount]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.EcoCommand
  pay:
    description: Pay an amout to a player
    usage: /pay [player] [amount]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.PayCommand
  paytoggle:
    description: Toggle if you accept or not payments
    usage: /paytoggle
    class: mc.owls.valley.net.feathercore.modules.economy.commands.PayToggleCommand
  withdraw:
    description: Withdraw money from player's balance in physical form
    usage: /withdraw [banknote-value] [amount]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.WithdrawCommand
  deposit:
    description: Deposit physical form of money to player's balance
    usage: /deposit [amount]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.DepositCommand
