name: FeatherCore
version: 0.5.0
main: mc.owls.valley.net.feathercore.core.FeatherCore
author: DefaultyBuf
description: Core plugin for server bukkit/spigot/paper servers

depend: [Vault]

api-version: 1.21.1

commands:
  balance:
    description: State the current balance of a given player
    usage: /balance <player>
    aliases: [bal]
  eco:
    description: Manage server economy
    usage: /eco give/take/set/reset [player] [amount]
  pay:
    description: Pay an amout to a player
    usage: /pay [player] [amount]
  paytoggle:
    description: Toggle if you accept or not payments
    usage: /paytoggle
  withdraw:
    description: Withdraw money from player's balance in physical form
    usage: /withdraw [banknote-value] [amount]
  deposit:
    description: Deposit physical form of money to player's balance
    usage: /deposit [amount]

  language:
    description: Set prefered language for messages
    usage: /language info/list/[language]
    aliases: [lang]

  lootchests:
    description: Manage loot chests
    usage: /lootchests [set/unset/create/delete/info/locations] <type> <display-name> <cooldown (seconds)>
