name: FeatherCore
version: 0.6.10
main: mc.owls.valley.net.feathercore.core.FeatherCore
author: DefaultyBuf
description: Core plugin for server bukkit/spigot/paper servers

depend: [Vault]

api-version: 1.21.1

commands:
  balance:
    description: State the current balance of a given player
    usage: /balance <player>
    aliases: [bal]
  eco:
    description: Manage server economy
    usage: /eco give/take/set/reset [player] [amount]
  pay:
    description: Pay an amout to a player
    usage: /pay [player] [amount]
  paytoggle:
    description: Toggle if you accept or not payments
    usage: /paytoggle
  withdraw:
    description: Withdraw money from player's balance in physical form
    usage: /withdraw [banknote-value] [amount]
  deposit:
    description: Deposit physical form of money to player's balance
    usage: /deposit [amount]

  language:
    description: Set prefered language for messages
    usage: /language info/list/[language]
    aliases: [lang]

  lootchests:
    description: Manage loot chests
    usage: /lootchests [set/unset/create/delete/info/locations] <type> <display-name> <cooldown (seconds)>

  feather-reload:
    description: Reload configurations
    usage: /feather-reload {MODULE}
    aliases: [fcreload]

  random-teleport:
    description: Teleport the player at a random location in the world
    usage: /random-teleport <world>
    aliases: [rtp]
  teleport-all:
    description: Teleport all players to the command sender
    usage: /teleport-all <player>
    aliases: [tpall]
  teleport:
    description: Teleport to a player, or teleport player1 to player2
    usage: /teleport <player1> <player2>
    aliases: [tp]
  teleport-here:
    description: Teleport the target player to command sender player
    usage: /teleport-here <player>
    aliases: [tphere]
  teleport-position:
    description: Teleport to specified position in the world
    usage: /teleport-position [x] [y] [z] <world>
    aliases: [tppos]
  teleport-last-location:
    description: Teleport to the last known location of the player
    usage: /teleport-last-location [destination-player] (who-player)
    aliases: [tplastknown]
  teleport-request:
    description: Request teleport to a player
    usage: /teleport-request <player>
    aliases: [tpa]
  teleport-here-request:
    description: Request teleport the target player to command sender player
    usage: /teleport-here-request <player>
    aliases: [tpahere]
  teleport-request-cancel:
    description: Cancel a sent teleport request
    usage: /teleport-request-cancel <player>
    aliases: [tpacancel]
  teleport-accept:
    description: Accept a teleport request
    usage: /teleport-accept <player>
    aliases: [tpaccept]
  teleport-deny:
    description: Deny a teleport request
    usage: /teleport-deny <player>
    aliases: [tpadeny]
