name: FeatherCore
version: 0.2.3
main: mc.owls.valley.net.feathercore.core.FeatherCore
author: DefaultyBuf
description: Core plugin for server bukkit/spigot/paper servers

depend: [Vault]

api-version: 1.21.1

feathercore:
  configs:
    - field: dataConfigFile
      config: data.yml
    - field: economyConfigFile
      config: economy.yml
  modules:
    - name: ConfigurationManager
      class: mc.owls.valley.net.feathercore.core.common.ConfigurationManager
      mandatory: true
      dependencies: []
    - name: MongoModule
      class: mc.owls.valley.net.feathercore.modules.data.mongodb.MongoModule
      mandatory: true
      dependencies: [ConfigurationManager]
    - name: PlayersDataModule
      class: mc.owls.valley.net.feathercore.modules.data.players.PlayersDataModule
      mandatory: true
      dependencies: [ConfigurationManager, MongoModule]
    - name: FeatherEconomyProviderModule
      class: mc.owls.valley.net.feathercore.modules.economy.provider.FeatherEconomyProviderModule
      mandatory: true
      dependencies: [PlayersDataModule]
    - name: VaultModule
      class: mc.owls.valley.net.feathercore.modules.economy.vault.VaultModule
      mandatory: true
      dependencies: [FeatherEconomyProviderModule]
    - name: CommandsRegistrator
      class: mc.owls.valley.net.feathercore.core.common.CommandsRegistrator
      mandatory: true
      dependencies: [ConfigurationManager, MongoModule, PlayersDataModule, FeatherEconomyProviderModule, VaultModule]

commands:
  balance:
    description: State the current balance of a given player
    usage: /balance <player>
    aliases: [bal]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.BalanceCommand
