name: FeatherCore
version: 0.2.2
main: mc.owls.valley.net.feathercore.core.FeatherCore
author: DefaultyBuf
description: Core plugin for server bukkit/spigot/paper servers

depend: [Vault]

api-version: 1.21.1

commands:
  balance:
    description: State the current balance of a given player
    usage: /balance <player>
    aliases: [bal]
    class: mc.owls.valley.net.feathercore.modules.economy.commands.BalanceCommand
